---

- name: reload ufw
  ufw:
    state: reloaded

- name: restart ssh
  service:
    name: ssh
    state: restarted

- name: restart ntp
  systemd:
    name: "{{ harden_linux_ntp }}"
    state: restarted
